services:
  blockscout-frontend:
    image: ghcr.io/blockscout/frontend:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    ports:
      - "9091:3000"
    environment:
      NEXT_PUBLIC_API_HOST: localhost
      NEXT_PUBLIC_API_PORT: 36001
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws

      NEXT_PUBLIC_APP_HOST: 0.0.0.0
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_APP_PORT: 3000

      NEXT_PUBLIC_AD_BANNER_PROVIDER: none
      NEXT_PUBLIC_AD_TEXT_PROVIDER: none

      NEXT_PUBLIC_NETWORK_NAME: Devnet
      NEXT_PUBLIC_NETWORK_SHORT_NAME: Devnet
      NEXT_PUBLIC_NETWORK_ID: 1337
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: Ether
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ETH
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18
      NEXT_PUBLIC_NETWORK_RPC_URL: http://localhost:34002
      NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: validation
      NEXT_PUBLIC_GAS_TRACKER_ENABLED: true
      NEXT_PUBLIC_HAS_BEACON_CHAIN: true
      NEXT_PUBLIC_IS_TESTNET: true
