[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "cancun"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "scripts"
solc = "0.8.28"
src = "src"
test = "tests"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./tests/fixtures" }]
ffi = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
dev = "http://localhost:${EL_RPC_PORT}"
